name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - starter/frontend/**
  #workflow_dispatch:  # Allow manual triggering
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Linting:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: Devlopment Environment

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: " 3.12.1"

    - name: Install Rependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Checkout Run Lint
      run: cd starter/backend && pipenv run lint
  Test:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: " 3.12.1"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Test
      run: cd starter/backend && pipenv install pytest && pipenv run test 
  Build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest
    environment: Devlopment Environment
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      working-directory: starter/backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag ${{ vars.REGISTRY }}/${{ vars.BACKEND_REPOSITORY }}:${{ vars.IMAGE_TAG }} .
        docker push ${{ vars.REGISTRY }}/${{ vars.BACKEND_REPOSITORY }}:${{ vars.IMAGE_TAG }}
    - name: Update Kubeconfig
      run:
       aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.CLUSTER }}

    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/backend/k8s
      run: |
        aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.CLUSTER }}
        kustomize edit set image backend=${{ vars.REGISTRY }}/${{ vars.BACKEND_REPOSITORY }}:${{ vars.IMAGE_TAG }}
        kustomize build | kubectl apply -f -
